import iCard from "./iCard";

export const HiraganaVocabulary: iCard[] = [
    {face: 'あい', back: 'ai', translation: 'love'},
    {face: 'うえ', back: 'ue', translation: 'up, above'},
    {face: 'いいえ', back: 'iie', translation: 'no'},
    {face: 'あおい', back: 'aoi', translation: 'blue'},
    {face: 'かく', back: 'kaku', translation: 'to write'},
    {face: 'かげ', back: 'kage', translation: 'shadow'},
    {face: 'きく', back: 'kiku', translation: 'to listen'},
    {face: 'こえ', back: 'koe', translation: 'voice'},
    {face: 'かぎ', back: 'kagi', translation: 'key'},
    {face: 'きおく', back: 'kioku', translation: 'memory'},
    {face: 'えいが', back: 'eiga', translation: 'movie'},
    {face: 'おおきい', back: 'ookii', translation: 'big'},
    {face: 'すし', back: 'sushi', translation: 'famouse japanese dish'},
    {face: 'じこ', back: 'jiko', translation: 'accident'},
    {face: 'すき', back: 'suki', translation: 'like'},
    {face: 'さく', back: 'saku', translation: 'bloom'},
    {face: 'ぞう', back: 'zo', translation: 'elephant'},
    {face: 'おかし', back: 'okashi', translation: 'sweets'},
    {face: 'おさけ', back: 'osake', translation: 'alcohol'},
    {face: 'さいご', back: 'saigo', translation: 'last'},
    {face: 'そおぞお', back: 'sozo', translation: 'imagination'},
    {face: 'こうこうせい', back: 'kokosei', translation: 'high school student'},
    {face: 'かさ', back: 'kasa', translation: 'umbrella'},
    {face: 'けす', back: 'kesu', translation: 'to erase'},
    {face: 'かそう', back: 'kasou', translation: 'to invite'},
    {face: 'かえす', back: 'kaesu', translation: 'to return'},
    {face: 'おす', back: 'osu', translation: 'to push'},
    {face: 'くじ', back: 'kuji', translation: 'lottery'},
    {face: 'おこす', back: 'okosu', translation: 'to wake someone up, to cause to happen'},
    {face: 'えさぎ', back: 'esagi', translation: 'rabbit'},
    {face: 'きし', back: 'kishi', translation: 'knight'},
    {face: 'しお', back: 'shio', translation: 'salt'},
    {face: 'すこし', back: 'sukoshi', translation: 'a little'},
    {face: 'さいせい', back: 'saisei', translation: 'playback'},
    {face: 'すご', back: 'sugo', translation: 'immediately'},
    {face: 'いしき', back: 'ishiki', translation: 'consciousness'},
    {face: 'さがす', back: 'sagasu', translation: 'to search'},
    {face: 'おかしい', back: 'okashii', translation: 'strange'},
    {face: 'すき', back: 'suki', translation: 'like'},
    {face: 'しごさ', back: 'shigosa', translation: 'gesture, mannerism'},
    {face: 'しかく', back: 'shikaku', translation: 'square'},
    {face: 'がくせい', back: 'gakusei', translation: 'student'},
    {face: 'かっこいい', back: 'kakoii', translation: 'cool'},
    {face: 'じっか', back: 'jika', translation: 'one\'s family home'},
    {face: 'かった', back: 'kata', translation: 'bought'},
    {face: 'かこ', back: 'kako', translation: 'past'},
    {face: 'じかん', back: 'jikan', translation: 'time'},
    {face: 'かた', back: 'kata', translation: 'shoulder'},
    {face: 'くつ', back: 'kutsu', translation: 'shoes'},
    {face: 'ちず', back: 'chizu', translation: 'map'},
    {face: 'でし', back: 'deshi', translation: 'apprentice'},
    {face: 'たつ', back: 'tatsu', translation: 'stand'},
    {face: 'とうい', back: 'toui', translation: 'far'},
    {face: 'つづく', back: 'tsudzuku', translation: 'to continue'},
    {face: 'どっち', back: 'dochi', translation: 'which'},
    {face: 'だいがく', back: 'daigaku', translation: 'university (big school)'},
    {face: 'あさって', back: 'asate', translation: 'the day after tomorrow'},
    {face: 'おちつく', back: 'ochitsuku', translation: 'to calm down'},
    {face: 'なに', back: 'nani', translation: 'what'},
    {face: 'いぬ', back: 'inu', translation: 'dog'},
    {face: 'ねこ', back: 'neko', translation: 'cat'},
    {face: 'にじ', back: 'niji', translation: 'rainbow'},
    {face: 'おかね', back: 'okane', translation: 'money'},
    {face: 'せなか', back: 'senaka', translation: 'upper back'},
    {face: 'なっとう', back: 'natou', translation: 'fermented soybeans'},
    {face: 'おねがい', back: 'onegai', translation: '"Please!", request(noun)'},
    {face: 'はな', back: 'hana', translation: 'flower'},
    {face: 'ひざ', back: 'hiza', translation: 'knee'},
    {face: 'はし', back: 'hashi', translation: 'chopsticks, bridge'},
    {face: 'ふしぎ', back: 'fushigi', translation: 'strange'},
    {face: 'はなび', back: 'hanabi', translation: 'fireworks (fire flowers)'},
    {face: 'ふくがつ', back: 'fukugatsu', translation: 'complicated'},
    {face: 'ひきだし', back: 'hikidashi', translation: 'drawer'},
    {face: 'けっぺき', back: 'kepeki', translation: 'perfectionist'},
    {face: 'まち', back: 'machi', translation: 'town, city'},
    {face: 'あめ', back: 'ame', translation: 'rain, candy'},
    {face: 'あたま', back: 'atama', translation: 'head'},
    {face: 'きもの', back: 'kimono', translation: 'something you wear'},
    {face: 'ためいき', back: 'tameiki', translation: 'sigh'},
    {face: 'まいにち', back: 'mainichi', translation: 'every day'},
    {face: 'むずかしい', back: 'muzukashii', translation: 'difficult'},
    {face: 'さる', back: 'saru', translation: 'monkey'},
    {face: 'はれ', back: 'hare', translation: 'sunny, clear weather'},
    {face: 'らく', back: 'raku', translation: 'convenient, comfortable'},
    {face: 'おふろ', back: 'ofuro', translation: 'bath'},
    {face: 'くすり', back: 'kusuri', translation: 'medicine'},
    {face: 'おにぎり', back: 'onigiri', translation: 'famouse japanese dish'},
    {face: 'ぬいぐるみ', back: 'nuigurumi', translation: 'stuffed toy'},
    {face: 'りゃう', back: 'ryu', translation: 'dragon'},
    {face: 'りやう', back: 'riyu', translation: 'reason'},
    {face: 'きょう', back: 'kyo', translation: 'today'},
    {face: 'きよう', back: 'kiyo', translation: 'handy, skilled'},
    {face: 'ゆめ', back: 'yume', translation: 'dream'},
    {face: 'やま', back: 'yama', translation: 'mountain'},
    {face: 'やすい', back: 'yasui', translation: 'cheap'},
    {face: 'りょうり', back: 'ryori', translation: 'cooking'},
    {face: 'かいしゃ', back: 'kaisha', translation: 'company'},
    {face: 'じゅうどう', back: 'judo', translation: 'type of martial art'},
    {face: 'しゅくだい', back: 'shukudai', translation: 'homework'},
    {face: 'びょいん', back: 'byoin', translation: 'hospital'},
    {face: 'かわ', back: 'kawa', translation: 'river'},
    {face: 'えん', back: 'en', translation: 'circle also Yen(currency)'},
    {face: 'わたし', back: 'watashi', translation: 'I, me'},
    {face: 'おんがく', back: 'ongaku', translation: 'music'},
    {face: 'しんぶん', back: 'shinbun', translation: 'newspaper'},
    {face: 'おかさん', back: 'okasan', translation: 'mother'},
    {face: 'みずをのむ', back: 'mizuwonomu', translation: 'to drink water'},
    {face: 'やさいわたべる', back: 'yasaiwataberu', translation: 'to eat vegetables'}
];