import iCard from "./iCard";

export const KanjiRadicalsN5: iCard[] = [
    {strokes: 0, face: '丨', back: 'ぼう', translation: 'line, stick'},
    {strokes: 0, face: '一', back: 'いち', translation: 'one'},
    {strokes: 0, face: '乙 (乚)', back: 'おつ', translation: 'the second'},
    {strokes: 0, face: '二', back: 'に', translation: 'two'},
    {strokes: 0, face: '人(亻)', back: 'にんべん', translation: 'person radical on the left'},
    {strokes: 0, face: '儿', back: 'にんにょう', translation: 'legs, human underneath'},
    {strokes: 0, face: '入 (𠆢)', back: 'いる', translation: 'to enter'},
    {strokes: 0, face: '八', back: 'はち', translation: 'eight'},
    {strokes: 0, face: '冂', back: 'まきがまえ', translation: 'inverted box, window frame'},
    {strokes: 0, face: '凵', back: 'うけばこ', translation: 'container, inbox'},
    {strokes: 0, face: '刀 (刂)', back: 'かたな（りっとう)', translation: 'sword, knife'},
    {strokes: 0, face: '匕', back: 'さじのひ', translation: 'spoon'},
    {strokes: 0, face: '十', back: 'じゅう', translation: 'ten, complete'},
    {strokes: 0, face: '又', back: 'また', translation: 'again'},
    {strokes: 0, face: '口', back: 'くち', translation: 'mouth, opening'},
    {strokes: 0, face: '囗', back: 'くにがまえ', translation: 'enclosure radical'},
    {strokes: 0, face: '土', back: 'つち', translation: 'earth, ground'},
    {strokes: 0, face: '夕', back: 'ゆうべ', translation: 'evening, sunset'},
    {strokes: 0, face: '大', back: 'だい', translation: 'big, very'},
    {strokes: 0, face: '女', back: 'おんな', translation: 'woman, female'},
    {strokes: 0, face: '子', back: 'こ', translation: 'child, seed'},
    {strokes: 0, face: '小 (⺌, ⺍)', back: 'ちいさい', translation: 'small, insignificant'},
    {strokes: 0, face: '山', back: 'やま', translation: 'mountain'},
    {strokes: 0, face: '巛 (川,巜)', back: 'かわ', translation: 'river'},
    {strokes: 0, face: '工', back: 'たくみ', translation: 'work'},
    {strokes: 0, face: '干', back: 'ほし', translation: 'dry'},
    {strokes: 0, face: '彳', back: 'ぎょうにんべん', translation: 'step'},
    {strokes: 0, face: '日', back: 'にち', translation: 'sun, day'},
    {strokes: 0, face: '曰', back: 'いわく', translation: 'say'},
    {strokes: 0, face: '月 (⺝)', back: 'つき', translation: 'moon, month; body, flesh'},
    {strokes: 0, face: '木', back: 'き', translation: 'tree'},
    {strokes: 0, face: '毋 (母,⺟)', back: 'なかれ (はは)', translation: 'do not; mother'},
    {strokes: 0, face: '气', back: 'きがまえ', translation: 'steam, breath'},
    {strokes: 0, face: '水 (氵,氺)', back: 'みず', translation: 'water'},
    {strokes: 0, face: '火 (灬)', back: 'ひ', translation: 'fire'},
    {strokes: 0, face: '父', back: 'ちち', translation: 'father'},
    {strokes: 0, face: '生', back: 'うまれる', translation: 'life'},
    {strokes: 0, face: '田', back: 'た', translation: 'rice field, rice patty'},
    {strokes: 0, face: '白', back: 'しろ', translation: 'white'},
    {strokes: 0, face: '行', back: 'ぎょう', translation: 'go, do'},
    {strokes: 0, face: '西 (襾,覀)', back: 'にし', translation: 'west'},
    {strokes: 0, face: '見', back: 'みる', translation: 'to see'},
    {strokes: 0, face: '言', back: 'こと', translation: 'speech'},
    {strokes: 0, face: '車', back: 'くるま', translation: 'cart, car'},
    {strokes: 0, face: '金 (釒)', back: 'かね', translation: 'metal, gold'},
    {strokes: 0, face: '長 (镸)', back: 'ながい (ちょう)', translation: 'long, grow (leader)'},
    {strokes: 0, face: '門', back: 'もん', translation: 'gate'},
    {strokes: 0, face: '雨 (⻗)', back: 'あめ', translation: 'rain'},
    {strokes: 0, face: '食 (飠,𩙿)', back: 'しょく', translation: 'eat, food'},
    {strokes: 0, face: '高 (髙)', back: 'たかい', translation: 'tall, high'}
];
