import iCard from "./iCard";

export const KanjiVocabularyN5: iCard[] = [
    {face: '一', back: {onYomi: 'イチ, イツ', kunYomi: 'ひと'}, translation: 'one'},
    {face: '七', back: {onYomi: 'シチ', kunYomi: 'なな'}, translation: 'seven'},
    {face: '万', back: {onYomi: 'マン', kunYomi: 'よろず'}, translation: 'ten thousand'},
    {face: '三', back: {onYomi: 'サン', kunYomi: 'み'}, translation: 'three'},
    {face: '上', back: {onYomi: 'ジョウ, ショウ', kunYomi: 'うえ, かみ'}, translation: 'up, above'},
    {face: '下', back: {onYomi: 'した', kunYomi: 'カ'}, translation: 'below, down, descend, give, low, inferior'},
    {face: '中', back: {onYomi: 'チュウ', kunYomi: 'なか'}, translation: 'in, inside, middle, mean, center'},
    {face: '九', back: {onYomi: 'キュウ, ク', kunYomi: 'ここの, ここのつ'}, translation: 'nine'},
    {face: '二', back: {onYomi: 'ニ ジ', kunYomi: 'ふた'}, translation: 'two'},
    {face: '五', back: {onYomi: 'ゴ', kunYomi: 'いつ, いつつ'}, translation: 'five'},
    {face: '人', back: {onYomi: 'ジン, ニン', kunYomi: 'ひと'}, translation: 'human, person'},
    {face: '今', back: {onYomi: 'コン, キン', kunYomi: 'いま'}, translation: 'now'},
    {face: '休', back: {onYomi: 'キュウ', kunYomi: 'やすむ, やすまる'}, translation: 'rest, day off, retire, sleep'},
    {face: '何', back: {onYomi: 'カ', kunYomi: 'なに, なん'}, translation: 'what'},
    {face: '先', back: {onYomi: 'セン', kunYomi: 'さき, まず'}, translation: 'before, ahead, previous, future, precedence'},
    {face: '入', back: {onYomi: 'ニュウ, ジュ', kunYomi: 'いる, いれる'}, translation: 'enter, insert'},
    {face: '八', back: {onYomi: 'ハチ', kunYomi: 'や, やつ'}, translation: 'eight'},
    {face: '六', back: {onYomi: 'ロク, リク', kunYomi: 'む, むつ'}, translation: 'six'},
    {face: '円', back: {onYomi: 'エン', kunYomi: 'まるい, まる'}, translation: 'circle, yen, round'},
    {face: '出', back: {onYomi: 'シュツ, スイ', kunYomi: 'でる, だす'}, translation: 'exit, leave, go out, come out, put out, protrude'},
    {face: '分', back: {onYomi: 'ブン, フン', kunYomi: 'わける, わけ'}, translation: 'part, minute of time, segment, share, degree, one\'s lot, duty, understand, know, rate, 1%, chances, shaku/100'},
    {face: '前', back: {onYomi: 'ゼン', kunYomi: 'まえ'}, translation: 'in front, before'},
    {face: '北', back: {onYomi: 'ホク', kunYomi: 'きた'}, translation: 'north'},
    {face: '十', back: {onYomi: 'ジュウ, ジッ', kunYomi: 'とお, と'}, translation: 'ten'},
    {face: '千', back: {onYomi: 'セン', kunYomi: 'ち'}, translation: 'thousand'},
    {face: '午', back: {onYomi: 'ゴ', kunYomi: 'うま'}, translation: 'noon, sign of the horse, 11AM-1PM, seventh sign of Chinese zodiac'},
    {face: '半', back: {onYomi: 'ハン', kunYomi: 'なかば'}, translation: 'half, middle, odd number, semi-, part-'},
    {face: '南', back: {onYomi: 'ナン, ナ', kunYomi: 'みなみ'}, translation: 'south'},
    {face: '友', back: {onYomi: 'ユウ', kunYomi: 'とも'}, translation: 'friend'},
    {face: '右', back: {onYomi: 'ウ, ユウ', kunYomi: 'みぎ'}, translation: 'right'},
    {face: '名', back: {onYomi: 'メイ, ミョウ', kunYomi: 'な'}, translation: 'name, noted, distinguished, reputation'},
    {face: '四', back: {onYomi: 'シ', kunYomi: 'よん'}, translation: 'four'},
    {face: '国', back: {onYomi: 'コク', kunYomi: 'くに'}, translation: 'country'},
    {face: '土', back: {onYomi: 'ド, ト', kunYomi: 'つち'}, translation: 'soil, earth, ground, Turkey'},
    {face: '外', back: {onYomi: 'ガイ, ゲ', kunYomi: 'そと, ほか'}, translation: 'outside'},
    {face: '大', back: {onYomi: 'ダイ, タイ', kunYomi: 'おおきい'}, translation: 'large, big'},
    {face: '天', back: {onYomi: 'テン', kunYomi: 'あまつ, あめ'}, translation: 'heavens, sky, imperial'},
    {face: '女', back: {onYomi: 'ジョ, ニョ', kunYomi: 'おんな, め'}, translation: 'woman, female'},
    {face: '子', back: {onYomi: 'シ, ス', kunYomi: 'こ, ね'}, translation: 'child, sign of the rat, 11PM-1AM, first sign of Chinese zodiac'},
    {face: '学', back: {onYomi: 'ガク', kunYomi: 'まなぶ'}, translation: 'study, learning, science'},
    {face: '小', back: {onYomi: 'ショウ', kunYomi: 'ちいさい'}, translation: 'little, small'},
    {face: '山', back: {onYomi: 'サン, セン', kunYomi: 'やま'}, translation: 'mountain'},
    {face: '川', back: {onYomi: 'セン', kunYomi: 'かわ'}, translation: 'stream, river, river or 3-stroke river radical (no. 47)'},
    {face: '左', back: {onYomi: 'サ, シャ', kunYomi: 'ひだり'}, translation: 'left'},
    {face: '年', back: {onYomi: 'ネン', kunYomi: 'とし'}, translation: 'year, counter for years'},
    {face: '後', back: {onYomi: 'ゴ, コウ', kunYomi: 'のち, うしろ'}, translation: 'behind, back, later'},
    {face: '日', back: {onYomi: 'ニチ, ジツ', kunYomi: 'ひ'}, translation: 'day, sun, Japan, counter for days'},
    {face: '時', back: {onYomi: 'ジ', kunYomi: 'とき'}, translation: 'time, hour'},
    {face: '書', back: {onYomi: 'ショ', kunYomi: 'かく'}, translation: 'write'},
    {face: '月', back: {onYomi: 'ゲツ, ガツ', kunYomi: 'つき'}, translation: 'month, moon'},
    {face: '木', back: {onYomi: 'ボク, モク', kunYomi: 'き'}, translation: 'tree, wood'},
    {face: '本', back: {onYomi: 'ホン', kunYomi: 'もと'}, translation: 'book, present, main, origin, true, real, counter for long cylindrical things'},
    {face: '来', back: {onYomi: 'ライ, タイ', kunYomi: 'くる, きたる'}, translation: 'come, due, next, cause, become'},
    {face: '東', back: {onYomi: 'トウ', kunYomi: 'ひがし'}, translation: 'east'},
    {face: '校', back: {onYomi: 'コウ, キョウ', kunYomi: ''}, translation: 'exam, school, printing, proof, correction'},
    {face: '母', back: {onYomi: 'ボ', kunYomi: 'はは, も'}, translation: 'mother'},
    {face: '毎', back: {onYomi: 'マイ', kunYomi: 'ごと'}, translation: 'every'},
    {face: '気', back: {onYomi: 'キ, ケ', kunYomi: 'いき'}, translation: 'spirit, mind, air, atmosphere, mood'},
    {face: '水', back: {onYomi: 'スイ', kunYomi: 'みず'}, translation: 'water'},
    {face: '火', back: {onYomi: 'カ', kunYomi: 'ひ'}, translation: 'fire'},
    {face: '父', back: {onYomi: 'フ', kunYomi: 'ちち'}, translation: 'father'},
    {face: '生', back: {onYomi: 'セイ, ショウ', kunYomi: 'いきる, いかす'}, translation: 'life, genuine, birth'},
    {face: '男', back: {onYomi: 'ダン, ナン', kunYomi: 'おとこ, お'}, translation: 'male'},
    {face: '白', back: {onYomi: 'ハク, ビャク', kunYomi: 'しろ, しろい'}, translation: 'white'},
    {face: '百', back: {onYomi: 'ヒャク, ビャク', kunYomi: 'もも'}, translation: 'hundred'},
    {face: '聞', back: {onYomi: 'ブン, モン', kunYomi: 'きく, きこえる'}, translation: 'hear, ask, listen'},
    {face: '行', back: {onYomi: 'コウ, ギョウ', kunYomi: 'いく, ゆく'}, translation: 'going, journey'},
    {face: '西', back: {onYomi: 'セイ, サイ', kunYomi: 'にし'}, translation: 'west, Spain'},
    {face: '見', back: {onYomi: 'ケン', kunYomi: 'み'}, translation: 'see, hopes, chances, idea, opinion, look at, visible'},
    {face: '話', back: {onYomi: 'ワ', kunYomi: 'はなす, はなし'}, translation: 'tale, talk'},
    {face: '語', back: {onYomi: 'ゴ', kunYomi: 'かたる, かたらう'}, translation: 'word, speech, language'},
    {face: '読', back: {onYomi: 'ドク, トク', kunYomi: 'よむ'}, translation: 'read'},
    {face: '車', back: {onYomi: 'シャ', kunYomi: 'くるま'}, translation: 'car'},
    {face: '金', back: {onYomi: 'キン, コン', kunYomi: 'かね'}, translation: 'gold'},
    {face: '長', back: {onYomi: 'チョウ', kunYomi: 'ながい, おさ'}, translation: 'long, leader'},
    {face: '間', back: {onYomi: 'カン, ケン', kunYomi: 'あいだ, ま'}, translation: 'interval, space'},
    {face: '雨', back: {onYomi: 'ウ', kunYomi: 'あめ'}, translation: 'rain'},
    {face: '電', back: {onYomi: 'デン', kunYomi: ''}, translation: 'electricity'},
    {face: '食', back: {onYomi: 'ショク, ジキ', kunYomi: 'くう, くらう'}, translation: 'eat, food'},
    {face: '高', back: {onYomi: 'コウ', kunYomi: 'たかい, たか'}, translation: 'tall, high, expensive'}
];