import iCard from "./iCard";

export const KanjiVocabularyN5: iCard[] = [
    {face: '一', back: 'イチ, イツ | ひと', translation: 'one'},
    {face: '七', back: 'シチ | なな', translation: 'seven'},
    {face: '万', back: 'マン | よろず', translation: 'ten thousand'},
    {face: '三', back: 'サン | み', translation: 'three'},
    {face: '上', back: 'ジョウ, ショウ | うえ, かみ', translation: 'up, above'},
    {face: '下', back: 'した | カ', translation: 'below, down, descend, give, low, inferior'},
    {face: '中', back: 'チュウ | なか', translation: 'in, inside, middle, mean, center'},
    {face: '九', back: 'キュウ, ク | ここの, ここのつ', translation: 'nine'},
    {face: '二', back: 'ニ ジ | ふた', translation: 'two'},
    {face: '五', back: 'ゴ | いつ, いつつ', translation: 'five'},
    {face: '人', back: 'ジン, ニン | ひと', translation: 'human, person'},
    {face: '今', back: 'コン, キン | いま', translation: 'now'},
    {face: '休', back: 'キュウ | やすむ, やすまる', translation: 'rest, day off, retire, sleep'},
    {face: '何', back: 'カ | なに, なん', translation: 'what'},
    {face: '先', back: 'セン | さき, まず', translation: 'before, ahead, previous, future, precedence'},
    {face: '入', back: 'ニュウ, ジュ | いる, いれる', translation: 'enter, insert'},
    {face: '八', back: 'ハチ | や, やつ', translation: 'eight'},
    {face: '六', back: 'ロク, リク | む, むつ', translation: 'six'},
    {face: '円', back: 'エン | まるい, まる', translation: 'circle, yen, round'},
    {face: '出', back: 'シュツ, スイ | でる, だす', translation: 'exit, leave, go out, come out, put out, protrude'},
    {face: '分', back: 'ブン, フン | わける, わけ', translation: 'part, minute of time, segment, share, degree, one\'s lot, duty, understand, know, rate, 1%, chances, shaku/100'},
    {face: '前', back: 'ゼン | まえ', translation: 'in front, before'},
    {face: '北', back: 'ホク | きた', translation: 'north'},
    {face: '十', back: 'ジュウ, ジッ | とお, と', translation: 'ten'},
    {face: '千', back: 'セン | ち', translation: 'thousand'},
    {face: '午', back: 'ゴ | うま', translation: 'noon, sign of the horse, 11AM-1PM, seventh sign of Chinese zodiac'},
    {face: '半', back: 'ハン | なかば', translation: 'half, middle, odd number, semi-, part-'},
    {face: '南', back: 'ナン, ナ | みなみ', translation: 'south'},
    {face: '友', back: 'ユウ | とも', translation: 'friend'},
    {face: '右', back: 'ウ, ユウ | みぎ', translation: 'right'},
    {face: '名', back: 'メイ, ミョウ | な', translation: 'name, noted, distinguished, reputation'},
    {face: '四', back: 'シ | よん', translation: 'four'},
    {face: '国', back: 'コク | くに', translation: 'country'},
    {face: '土', back: 'ド, ト | つち', translation: 'soil, earth, ground, Turkey'},
    {face: '外', back: 'ガイ, ゲ | そと, ほか', translation: 'outside'},
    {face: '大', back: 'ダイ, タイ | おおきい', translation: 'large, big'},
    {face: '天', back: 'テン | あまつ, あめ', translation: 'heavens, sky, imperial'},
    {face: '女', back: 'ジョ, ニョ | おんな, め', translation: 'woman, female'},
    {face: '子', back: 'シ, ス | こ, ね', translation: 'child, sign of the rat, 11PM-1AM, first sign of Chinese zodiac'},
    {face: '学', back: 'ガク | まなぶ', translation: 'study, learning, science'},
    {face: '小', back: 'ショウ | ちいさい', translation: 'little, small'},
    {face: '山', back: 'サン, セン | やま', translation: 'mountain'},
    {face: '川', back: 'セン | かわ', translation: 'stream, river, river or 3-stroke river radical (no. 47)'},
    {face: '左', back: 'サ, シャ | ひだり', translation: 'left'},
    {face: '年', back: 'ネン | とし', translation: 'year, counter for years'},
    {face: '後', back: 'ゴ, コウ | のち, うしろ', translation: 'behind, back, later'},
    {face: '日', back: 'ニチ, ジツ | ひ', translation: 'day, sun, Japan, counter for days'},
    {face: '時', back: 'ジ | とき', translation: 'time, hour'},
    {face: '書', back: 'ショ | かく', translation: 'write'},
    {face: '月', back: 'ゲツ, ガツ | つき', translation: 'month, moon'},
    {face: '木', back: 'ボク, モク | き', translation: 'tree, wood'},
    {face: '本', back: 'ホン | もと', translation: 'book, present, main, origin, true, real, counter for long cylindrical things'},
    {face: '来', back: 'ライ, タイ | くる, きたる', translation: 'come, due, next, cause, become'},
    {face: '東', back: 'トウ | ひがし', translation: 'east'},
    {face: '校', back: 'コウ, キョウ', translation: 'exam, school, printing, proof, correction'},
    {face: '母', back: 'ボ | はは, も', translation: 'mother'},
    {face: '毎', back: 'マイ | ごと', translation: 'every'},
    {face: '気', back: 'キ, ケ | いき', translation: 'spirit, mind, air, atmosphere, mood'},
    {face: '水', back: 'スイ | みず', translation: 'water'},
    {face: '火', back: 'カ | ひ', translation: 'fire'},
    {face: '父', back: 'フ | ちち', translation: 'father'},
    {face: '生', back: 'セイ, ショウ | いきる, いかす', translation: 'life, genuine, birth'},
    {face: '男', back: 'ダン, ナン | おとこ, お', translation: 'male'},
    {face: '白', back: 'ハク, ビャク | しろ, しろい', translation: 'white'},
    {face: '百', back: 'ヒャク, ビャク | もも', translation: 'hundred'},
    {face: '聞', back: 'ブン, モン | きく, きこえる', translation: 'hear, ask, listen'},
    {face: '行', back: 'コウ, ギョウ | いく, ゆく', translation: 'going, journey'},
    {face: '西', back: 'セイ, サイ | にし', translation: 'west, Spain'},
    {face: '見', back: 'ケン | み', translation: 'see, hopes, chances, idea, opinion, look at, visible'},
    {face: '話', back: 'ワ | はなす, はなし', translation: 'tale, talk'},
    {face: '語', back: 'ゴ | かたる, かたらう', translation: 'word, speech, language'},
    {face: '読', back: 'ドク, トク | よむ', translation: 'read'},
    {face: '車', back: 'シャ | くるま', translation: 'car'},
    {face: '金', back: 'キン, コン | かね', translation: 'gold'},
    {face: '長', back: 'チョウ | ながい, おさ', translation: 'long, leader'},
    {face: '間', back: 'カン, ケン | あいだ, ま', translation: 'interval, space'},
    {face: '雨', back: 'ウ | あめ', translation: 'rain'},
    {face: '電', back: 'デン', translation: 'electricity'},
    {face: '食', back: 'ショク, ジキ | くう, くらう', translation: 'eat, food'},
    {face: '高', back: 'コウ | たかい, たか', translation: 'tall, high, expensive'}
];