import iCard from "./iCard";

export const KatakanaWords: iCard[] = [
    {face: 'エコ', back: 'eko', translation: 'eco-friendly'},
    {face: 'ギア', back: 'giya', translation: 'gear'},
    {face: 'カカオ', back: 'kakao', translation: 'cacao'},
    {face: 'ケーキ', back: 'keーki', translation: 'cake'},
    {face: 'カーカー', back: 'kaーkaー', translation: 'crow\'s crow'},
    {face: 'イケてる', back: 'iketeru', translation: 'cool, sexy'},
    {face: 'グーグー', back: 'guーguー', translation: '*stomach growl*'},
    {face: 'オーケー', back: 'oーkeー', translation: 'okay'},
    {face: 'ガス', back: 'gasu', translation: 'gas (gasoline)'},
    {face: 'アジア', back: 'ajia', translation: 'asia'},
    {face: 'スキー', back: 'sukiー', translation: 'ski'},
    {face: 'コース', back: 'koーsu', translation: 'course'},
    {face: 'ソース', back: 'soーsu', translation: 'sauce or source'},
    {face: 'カサカサ', back: 'kasakasa', translation: '*rustling* or dry'},
    {face: 'ウィスキー', back: 'uisukiー', translation: 'whiskey'},
    {face: 'シェアスる', back: 'sheasuru', translation: 'to share'},
    {face: 'タイ', back: 'tai', translation: 'Thailand'},
    {face: 'チーズ', back: 'chiーzu', translation: 'cheese'},
    {face: 'デート', back: 'deーto', translation: '(romantic) date'},
    {face: 'ドイツ', back: 'doitsu', translation: 'Germany'},
    {face: 'スイッチ', back: 'suichi', translation: 'switch'},
    {face: 'サッカー', back: 'sakaー', translation: 'soccor'},
    {face: 'アウトドア', back: 'autodoa', translation: 'outdoor activities'},
    {face: 'ジェットコースター', back: 'jetokoーsutaー', translation: 'roller coaster'},
    {face: 'ツナ', back: 'tsuna', translation: 'tuna'},
    {face: 'ネタ', back: 'neta', translation: 'joke material or punchline'},
    {face: 'ノート', back: 'noーto', translation: 'notebook'},
    {face: 'シニア', back: 'shinia', translation: 'elderly people'},
    {face: 'カヌー', back: 'kanuー', translation: 'canoe'},
    {face: 'ネット', back: 'neto', translation: 'internet'},
    {face: 'ニコニコ', back: 'nikoniko', translation: 'smiling from ear to ear'},
    {face: 'デザイヌー', back: 'dezainaー', translation: 'designer'},
    {face: 'ベース', back: 'beーsu', translation: 'bass(instrument) or base(baseball)'},
    {face: 'サベる', back: 'saberu', translation: 'to slack off'},
    {face: 'コーヒー', back: 'koーhiー', translation: 'coffee'},
    {face: 'デパート', back: 'depaーto', translation: 'department store'},
    {face: 'ビジェネス', back: 'bijenesu', translation: 'business'},
    {face: 'パーティー', back: 'paーtiー', translation: 'party'},
    {face: 'ピカピカ', back: 'pikapika', translation: 'shiny, sparkling'},
    {face: 'ゴボゴボ', back: 'gobogbo', translation: '*rushing water*'},
    {face: 'スマート', back: 'samaーto', translation: 'smart looking'},
    {face: 'ゲーム', back: 'geーmu', translation: 'games'},
    {face: 'スマホ', back: 'sumaho', translation: 'smart phone(abbreviation)'},
    {face: 'メモる', back: 'memoru', translation: 'to take a memo/note'},
    {face: 'イメージ', back: 'imeーji', translation: 'illustration(drawn)'},
    {face: 'デジカメ', back: 'dejikame', translation: 'digital camera(abbreviation)'},
    {face: 'マスコミ', back: 'masukomi', translation: 'mass communication(abbreviation), media'},
    {face: 'ケしゴム', back: 'keshigomu', translation: 'eraser'},
    {face: 'メキシコ', back: 'mekishiko', translation: 'Mexico'},
    {face: 'ホテル', back: 'hoteru', translation: 'hotel'},
    {face: 'トイレ', back: 'toire', translation: 'toilet'},
    {face: 'テレビ', back: 'terebi', translation: 'TV'},
    {face: 'カレオケ', back: 'karaoke', translation: 'karaoke'},
    {face: 'イギリス', back: 'igirisu', translation: 'United Kingdom'},
    {face: 'アルバイト', back: 'arubaito', translation: 'part-time work'},
    {face: 'プロポーズする', back: 'puropoーzusuru', translation: 'to propose marriage'},
    {face: 'クレジットカード', back: 'kurejitokaーdo', translation: 'credit card'},
    {face: 'ダイヤ', back: 'daiya', translation: 'bus/train time table'},
    {face: 'メニュー', back: 'menuー', translation: 'menu'},
    {face: 'ジュース', back: 'juーsu', translation: 'juice'},
    {face: 'Tシャツ', back: 'Tshatsu', translation: 't-shirt'},
    {face: 'バーベキュー', back: 'baーbekyuー', translation: 'barbecue'},
    {face: 'チョコレート', back: 'chokoreーto', translation: 'chocolate'},
    {face: 'ニャーニャー', back: 'nyaーnyaー', translation: 'cat\'s meow'},
    {face: 'キャッシュカード', back: 'kyashukaーdo', translation: 'bank card'},
    {face: 'コンビニ', back: 'combini', translation: 'convenience store'},
    {face: 'ワイワイ', back: 'waiwai', translation: 'noisy crowd'},
    {face: 'エアコン', back: 'eakon', translation: 'AC (air conditioning)'},
    {face: 'ラーメン', back: 'raーmen', translation: 'ramen'},
    {face: 'ワンワン', back: 'wanwan', translation: 'dog\'s bark'},
    {face: 'プレゼント', back: 'puresento', translation: 'gift'},
    {face: 'コンタクト', back: 'kontakuto', translation: 'contact lenses'},
    {face: 'サラリーマン', back: 'sarariーman', translation: 'salary man'},
];